spring.application.name=chat

spring.datasource.url=jdbc:postgresql://localhost:5432/kodachat
spring.datasource.username=koda
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect